set_property PACKAGE_PIN R14 [get_ports {omono_0[3]}]
set_property PACKAGE_PIN P14 [get_ports {omono_0[2]}]
set_property PACKAGE_PIN N16 [get_ports {omono_0[1]}]
set_property PACKAGE_PIN M14 [get_ports {omono_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {omono_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {omono_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {omono_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {omono_0[0]}]

set_property PACKAGE_PIN N15 [get_ports {orgb4_0[0]}]
set_property PACKAGE_PIN G17 [get_ports {orgb4_0[1]}]
set_property PACKAGE_PIN L15 [get_ports {orgb4_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {orgb4_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {orgb4_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {orgb4_0[2]}]
